In [1]:
#Q1. Write a Python Program to Add Two Matrices?


import numpy as np

mat1 = np.array([[1,4,6],
        [7,5,88],
        [8,5,77]])
mat2 = np.array([[12,43,74],
        [5,8,3],
        [8,9,9]])

Matsum = np.add(mat1,mat2)
print("The Sum of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(mat1,mat2,Matsum))
     

The Sum of two matrix 

[[ 1  4  6]
 [ 7  5 88]
 [ 8  5 77]]  and 

[[12 43 74]
 [ 5  8  3]
 [ 8  9  9]]  is 

[[13 47 80]
 [12 13 91]
 [16 14 86]] 


In [2]:
#Q2. Write a Python Program to Multiply Two Matrices?


import numpy as np

mat1 = np.array([[13,42,64],
        [3,7,4],
        [9,1,2]])
mat2 = np.array([[2,4,7],
        [55,67,8],
        [8,9,1]])

mulMat = np.dot(mat1,mat2)
print("The product of two matrix \n\n{}  and \n\n{}  is \n\n{} ".format(mat1,mat2,mulMat))

The product of two matrix 

[[13 42 64]
 [ 3  7  4]
 [ 9  1  2]]  and 

[[ 2  4  7]
 [55 67  8]
 [ 8  9  1]]  is 

[[2848 3442  491]
 [ 423  517   81]
 [  89  121   73]] 


In [4]:
#Q4. Write a Python Program to Sort Words in Alphabetic Order?


Arr = input("Enter string: ")

words = Arr.split()
words.sort()
for word in words:
    print(word)

Enter string: hnsjh ksiis yyykkks yybs
hnsjh
ksiis
yybs
yyykkks


In [5]:
#Q5. Write a Python Program to Remove Punctuation From a String?


punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

Arr = input("Enter a string with punctuations")


rem_punc = ""
for i in Arr:
    if i not in punctuations:
        rem_punc = rem_punc + i

# display 
print(rem_punc)

Enter a string with punctuations"sidh.art/h.ku'mar';ybsj
sidharthkumarybsj
